<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "polpo_theme"
 *
 * Auto generated by Extension Builder 2017-10-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'JKRV Webseiten Template',
    'description' => 'Webseiten-Template des Jenaer Kanu- und Rudervereins e.V.
Basierend auf Botostrap Version 4',
    'category' => 'distribution',
    'author' => 'Sebastian Jung',
    'author_email' => 'jung.jena@gmx.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.0.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
